CREATE TABLE IF NOT EXISTS FUNCIONARIO (
    CODIGO BIGINT(10) PRIMARY KEY IDENTITY,
    DESCRICAO VARCHAR(100) NOT NULL,
    SITUACAO_FUNCIONARIO INT NOT NULL,
    DATA_ADMISSAO TIMESTAMP NOT NULL,
    CEP VARCHAR(8) NOT NULL,
    LOGRADOURO VARCHAR(100) NOT NULL,
    COMPLEMENTO VARCHAR(100),
    BAIRRO VARCHAR(100) NOT NULL,
    LOCALIDADE VARCHAR(100) NOT NULL,
    UF VARCHAR(2) NOT NULL,
    NUMERO VARCHAR(10),
    OCUPACAO_FK INT NOT NULL,
    EMPRESA_FK INT NOT NULL,
    FOREIGN KEY (OCUPACAO_FK) REFERENCES OCUPACAO(CODIGO),    
    FOREIGN KEY (EMPRESA_FK) REFERENCES EMPRESA(CODIGO)    
);