CREATE TABLE IF NOT EXISTS EMPRESA {
    CODIGO BIGINT(10) PRIMARY KEY IDENTITY,
    CNPJ VARCHAR(14) NOT NULL,
    NOME_FANTASIA VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL
}