CREATE TABLE IF NOT EXISTS EMPRESA {
    CODIGO BIGINT(10) PRIMARY KEY IDENTITY,
    CNPJ VARCHAR(14) NOT NULL,
    NOME_FANTASIA VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    CEP VARCHAR(8) NOT NULL,
    LOGRADOURO VARCHAR(100) NOT NULL,
    COMPLEMENTO VARCHAR(100),
    BAIRRO VARCHAR(100) NOT NULL,
    LOCALIDADE VARCHAR(100) NOT NULL,
    UF VARCHAR(2) NOT NULL,
    NUMERO VARCHAR(10)
}