CREATE TABLE PUBLIC.CONTA (
    CODIGO BIGINT(10) PRIMARY KEY IDENTITY,
    AGENCIA VARCHAR(10) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    DIGITO VARCHAR(2) NOT NULL,
    SALDO DECIMAL(19,5) NOT NULL, 
    BANCO_FK INT NOT NULL,
    FOREIGN KEY (BANCO_FK) REFERENCES PUBLIC.BANCO(ID)
);